### ISSUE TITLE
Unable to download animas_AOI_prms in test.ebagis

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/django-ebagis#44]
Download url: https://test.ebagis.geog.pdx.edu/api/rest/downloads/ad645063-ac53-4661-90f2-6f941e3cfed4/

This is a larger AOI. It seems to hang at about 23,000 kb and I eventually get the following error about the connection being closed by the remote host. I am trying to download the zip file in one big chunk.

{System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Net.WebClient.DownloadBitsReadCallbackState(DownloadBitsState state, IAsyncResult result)
   --- End of inner exception stack trace ---}

**Comment by lbross** [comment]
Tried to download this AOI today and got same error message. Can you check logs on server?

**Comment by jkeifer** [comment]
I can certainly reproduce this issue, but the logs are not helpful. I am uncertain what the problem is at the moment, but it certainly is on the server side, in case there was any doubt.

**Comment by jkeifer** [comment]
I am still not certain why this was failing. Rather than waste my time trying to figure that out, I knew the way I was serving the files was not good, so instead I thought it best to change the whole way that was setup. I had previously implemented a better method, but it had some bugs. (Unfortunately, IIS makes it hard to serve files behind django in a good way (unlike apache or nginx), so the only good solution I could find was to roll-my-own.)

After too long a time debugging, I identified and fixed the errors, then got the code running on the test instance. Downloading the link posted above works on my mac, where previously it would fail at a seemingly random point in the file, never more that 24MB or so.

Also, I might add, the new method for serving files is waaay faster and uses waaay less memory, quantitatively speaking.

@lbross please give it a try and let me know if my changes work for you.

(The original commit for this work is 950a6a5e27f42f728d033fe183f334311c373691, but that was on the dev branch, so I cherry-picked it onto master with commit f0317c1216139a00344923906be00a55e89a8eac).

**Comment by lbross** [comment]
Tested and fixed
