### ISSUE TITLE
Unable to upload animas_AOI_prms in test.ebagis

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/django-ebagis#53]
The inverse of issue #44. This is the same AOI but I am trying to upload it again because the database got wiped. It is a large AOI. This is the only error I'm getting on the client-side. Do you see anything on the server?

{System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at BAGIS_ClassLibrary.WebservicesModule.BA_UploadMultiPart(String webserviceUrl, String strToken, String fileName, String filePath, String comment)

**Comment by jkeifer** [comment]
I took a look at this and all I could find in the logs that might be related to this issue was one upload that failed with a 500 error:

```
2016-04-05 18:47:17 131.252.97.90 POST /api/rest/aois/ - 443 - 131.252.234.254 - - 500 0 64 104413 multipart/form-data;+boundary=---------------------------8d35d47cbf28e19
```

I am not sure what time you tried to upload this one, so I don't know if the time stamp matches (it's in UTC). I did not see any other failed uploads in the logs.

If you only tried to upload one, please try again. I uploaded a couple large AOIs without using chunks and had no issues (I don't know if I have the AOI you mention, but I did find an upload zip file that's 53,645 KB (the name is a UUID, so I can't tell what it actually is)).

If you continue to have issues can you drop the zip somewhere on the server so I can try it out?

**Comment by jkeifer** [comment]
Any word on this?

**Comment by lbross** [comment]
Just retried on test.ebagis and failed with a 500 error. Timestamp 3:45p on April 11. Will try on ebagis just for the heck of it.

**Comment by jkeifer** [comment]
How big is the zip file? I have a suspicion it might be a limit set in IIS, but I won't be able to confirm that until later.

**Comment by lbross** [comment]
Zip file size is 54,000 KB. I just uploaded it successfully to ebagis! Do you still me to post it somewhere else? Or can you download it from there?

**Comment by jkeifer** [comment]
I think I should be able to find the file. Just to confirm, all other uploads you've tried are working as expected?

I will take a look and see what I can find regarding this error. It definitely seems to be in IIS rather than the django process given that I could only find it logged in IIS previously. I think I probably missed a setting in the test.ebagis web config that prevents large uploads (or set it incorrectly).

**Comment by lbross** [comment]
I haven't done extensive testing on either server today. But yes, that seems to be the only one having issues.

**Comment by jkeifer** [comment]
@lbross Is this still an issue for you? I've confirmed the upload file size limit in IIS is 1 GB for both test and non-test ebagis, and I've been able to successfully upload the provided zip to both.

**Comment by lbross** [comment]
Wish I had a definitive answer. I've spent the last hour or so trying to upload this file under different names to both servers. Sometimes it works and sometimes it doesn't. No pattern. When it fails, it usually throws a 500 error. The failure seems to occur in the middle of the upload process. Do you see anything in the logs that might give us a clue? I wonder if it's some sort of network glitchiness and it's manifesting in this case because we need to keep the pipe open so long.

**Comment by jkeifer** [comment]
@lbross So I've dug into this and the logs are generally unhelpful. Here are some examples of failed uploads:

```
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken Content-Type
2016-05-24 20:10:38 131.252.97.90 POST /api/rest/aois/ - 443 - 131.252.234.24 - - 500 0 258 94669 multipart/form-data;+boundary=---------------------------8d383d494c205a9
2016-05-24 20:19:31 131.252.97.90 POST /api/rest/aois/ - 443 - 131.252.234.24 - - 500 0 2147500037 92664 multipart/form-data;+boundary=---------------------------8d383d5d3a62942
```

The `sc-win32-status` field is a windows error message, and all the upload requests with 500 responses that I have found had a non-zero value in this field, specifically 258 or 2147500037. Neither really helps determine what is going wrong: the 258 is a `WAIT_TIMEOUT` that might suggest a problem with the TCP session (though I would expect an error 64 instead), and 2147500037 is not a valid error code (it is curiously close to the max int on windows, though is actually greater than it by 16390, which itself is beyond the range of valid error codes).

The idea of network issues is intriguing, though I don't suspect you would have such serious network issues and not notice on other things. TCP is a very resilient protocol and it takes a fair bit of interruption to drop a session. Moreover, you get a response back from the server, so I believe that would mean your session is still up. Nonetheless, if really you wanted to eliminate network issues from consideration, run the BAGIS uploader on Basins directly and see what happens.

The other thing that may help is capturing the whole response the server returns. IIS sometimes provides some useful debugging information in its 500 responses, which might help narrow down the issue. Can you setup a debug flag in your code that will write the whole response to a local file in the event of a failure?

The last little bit I'll mention: because these requests are interrupted before completion, nothing is ever forwarded to the django application, instead it is all dropped by IIS. Consequently, I can say pretty definitively that the issue is either in your upload code, in IIS (either itself or a configuration problem), or with something between the two.

If you can't easily get the 500 responses captured to a local file, I can try to put together a test program to  see what I can turn up.

**Comment by lbross** [comment]
Not much here but attaching the complete 500 response as requested. The first couple of lines are added by me.
[upload_error.txt](https://github.com/PSU-CSAR/django-ebagis/files/310006/upload_error.txt)

**Comment by lbross** [comment]
Just uploaded twice in a row using the PC client from BASINS and no issues. I do suspect it's some sort of a network issue with big files because I don't have any issues with smaller ones. The right answer is probably to use the chunked uploader functionality but I don't know how this would work with VB .Net. I'll add it to my list.

**Comment by jkeifer** [comment]
I just had a chance to take a look at the error out you posted, and I have to apologize. I completely forgot that the error messages IIS serves contain no relevant information unless the request comes from the same host, i.e., the request was generated locally on the server.

I think using the chunked upload is all around a better idea for a number of reasons. Even so, I'm still having issues thinking it would be a network problem. It certainly could be, but TCP is pretty reliable.

I'm sure you don't want to waste more time testing this, but in case you run into the problem again, or have other issues with IIS-related 500 errors, I setup failed request tracing. The tracing module is not installed with IIS by default, so I didn't find it before when I was poking around. But some googling brought it to my attention, and I've gotten it setup to provide enhanced logging for 500 errors.

A quick test shows that it is working, though at first glance the output is extremely comprehensive and very difficult to parse. Nonetheless, it's running on the test instance in case we need it.

For reference, the log files are being written in xml format to `D:\projects\ebagis\testing\ebagis_beta\django-ebagis-site\W3SVC4`. Double-clicking one will open it in IE for browsing.

**Comment by lbross** [comment]
Could I get some guidance on how to use the chunked upload? I found an e-mail from 26 March 2015 that says to use the same URL with a POST for both types of uploads. api/rest/aois/. And it says to send a POST at the end with the md5 to indicated that all chunks have been uploaded. How does the service know if I'm doing a full or partial upload? Is it that the md5 isn't included in the initial request for a partial? Or?

**Comment by jkeifer** [comment]
I can try to provide more detail later if you need it, but for the moment in case it will help you out:

Here is a sample python script that I use for testing uploads: https://github.com/PSU-CSAR/sample-chunked-upload/blob/master/uptest.py

From that code, it looks that you do a PUT to `api/rest/aois/`. Be sure to include the `Content-Range` in the header.

That first PUT will return the url of the upload object. For each successive chunk PUT that chunk to that upload url. Again, be sure to set the `Content-Range` appropriately in the header. Every PUT will return an offset telling you what the last byte written was; you'll likely want to verify that is correct after each chunk, and if not, then re-PUT it.

Once you have sent the last chunk, you then POST to the upload url. You'll need to include the md5 in the request at this point. The POST is the signal to the upload endpoint that the upload is completed (which is why when you don't use chunks you just do a single POST).

**Comment by lbross** [comment]
This does help me out. PUT vs POST makes sense that they would be handled differently. I tried this afternoon to just do a PUT with the whole file (a smaller one) to see if I could get the url back. There's not a lot of doc on VB .NET and PUT so I am probably doing something wrong. But if you have a chance to take a look at the error and see if it's something obvious, that would be great. I know I am at least getting to the service.

This is the error, I think: Exception Value: This QueryDict instance is immutable

**Comment by jkeifer** [comment]
@lbross I finally had a chance to look into this. The error that you posted is on my end of things, but I cannot figure out why it is occurring when you send the request and doesn't occur when I do so. I'm pretty sure it is some subtle difference in the way the request is sent or the HTTP headers that is making the backend framework create an immutable data structure rather than a mutable one, which causes a problem when I try to mutate it.

I'm going to keep working on it and see if I can get anywhere. Is this new code on github somewhere where I could take a look at it?

**Comment by jkeifer** [comment]
@lbross I implemented what I believe is a solution for this issue. However, as I am not sure why it was happening in the first place, I cannot actually verify if I fixed it or not. Can you give it a try with your uploader and let me know what happens?

**Comment by lbross** [comment]
Thanks for working this @jkeifer. Just tried again and got a different error message: {"detail":{"file":["The submitted data was not a file. Check the encoding type on the form."]}}}. I think this is a problem on my side. Will keep you posted.

**Comment by lbross** [comment]
What all should be included in the Content-Range attribute on the initial request. In addition to the file bytes, I am also sending a couple of form fields: fileName and comments delineated by "&". Should the length of these bytes be added to the file length for the Content-Range?

**Comment by jkeifer** [comment]
No, the `Content-Range` is just for the file bytes you are sending (it is used by the backend to determine where in the output file to put the chunk you are sending). `Content-Length` would be the total length of the request, I believe.

Note that the field names for the file name and the comment are `filename` and `comment`.

**Comment by lbross** [comment]
OK. I think I'm setting the Content-Range correctly but am now getting the following error: "The operation has timed out" on a small AOI. I have a feeling this is coming from IIS, but not sure. I'm intentionally not sending the md5 because, at this point, I just want to see if the PUT works and I want to get the url of the upload object. Thanks.

**Comment by lbross** [comment]
Taking another stab at this today. Now I am getting a 400 from IIS with no information in the response. I switched my code back to try a full upload to see if that still works and my request is stuck. I checked the task manager and it looks like both the celery instances are running but my upload task never goes beyond pending.

Also, any suggestions for tracking down the 400 error? Checked the httperr.log file in the C:\Windows\System32\LogFiles\HTTPERR directory but am not finding anything helpful there. Nor in request tracing log. But I'm not surprised about the latter because I think it's not getting that far.

**Comment by lbross** [comment]
@jkeifer: I got this working today through curl! And am making progress with VB .NET. What is your recommendation for chunk size? In your Python script you use 4MB.

**Comment by jkeifer** [comment]
@lbross Glad to hear you're making progress.

I don't have much of a recommendation on chunk size. The idea is to pick something that is big enough the repeated HTTP requests don't cause undue overhead, and something small enough that is isn't too painful to retry a chunk upon failure. Additionally, given the timeout problems you've experienced, you also want a chunk that will complete before timing out.

The 4 MB size is simply what it seemed like a few people were using when I did my research to implement the chunking, but I didn't do anything to determine the best practices around that size.

4 MB on a 5 Mbps connection, assuming the full throughput is available, is about 6.4 seconds. That's not too bad a time for an HTTP connection to hang open. Worst case, the connection slows down to 25% that speed or something and it takes 30 seconds to transfer one chunk. That's getting up there in time, but again, if you can assume your users should have more bandwidth than that, 4 MB is safe.

If you want to work with slower connections than that, then I'd say a smaller chunk would be more appropriate. If you're not sure what they'll have for throughput at NWCC and need to ensure their uploads will work even at slow speeds, go with 1 or 2 MB chunks. For faster connections, a larger chunk is more efficient, though I don't think I'd go larger than 4 MB unless you had a good reason for it.

**Comment by lbross** [comment]
@jkeifer: Going with 4MB for now just to get it working. Yesterday I did a single PUT request to prove that out. Today I'm trying to send chunks. I am getting this error message: Offsets do not match: offset 4097. I'm probably just off in the bytes I am sending but can you give me a little more info on this error message? The content-range for this packet is 'bytes 4098-8195/59850810'

**Comment by jkeifer** [comment]
@lbross Yeah, you are interpreting that error correctly, it means the offset on the server side does not match that in the content-range. It looks like you should be at 4097 for the first byte in your next request, as the count is 0-indexed.

Also, it seems your chunk is actually 4 kB, not MB...multiply again by 1024?

**Comment by lbross** [comment]
@jkeifer: Continuing to make progress but not getting the right checksum. Not sure if I am chunking the file correctly. Here are examples of the content-range in the first few chunks:

bytes 0-4194304/59850810
bytes 4194304-8388608/59850810
bytes 8388608-12582912/59850810

It seems illogical to me that the ending range for one would be the beginning range for the next because that seems to duplicate the byte but maybe I am missing something? The server seems to be happy with it.

**Comment by jkeifer** [comment]
I believe you are correct, I think it's my turn to have an off-by-one error, this time on the end byte parameter. I have been simply setting that to be be `current_position + chunk_size`, but that, as you see, leads to this strange situation where the "end" of one is the beginning of the next.

Rather, it should be `current_position + (chunk_size - 1)` to calculate the end position. I'll have to update the server side though to allow this change, as it is doing the same thing to validate the received chunk matches the range specified in the header. I'll try to do so this evening.

**Comment by lbross** [comment]
@jkeifer. Checking in for status. Would be great to get this working, finally. I think we're close.

**Comment by jkeifer** [comment]
@lbross Sorry, I should have let you know. I got sick and didn't get to the work I promised. I think it should be a really quick change with a bit more testing. Assuming I don't have any surprises I'm going to say it'll be done for sure before the end of the week. Hopefully sooner, like tonight.

**Comment by jkeifer** [comment]
@lbross Alright, I think this should be good to go for you. Now the ending byte should be one less than the starting byte for the next chunk.

Let me know if you have any problems.

**Comment by lbross** [comment]
@jkeifer  Thanks! Now I'm getting this message with the first chunk. Any ideas? The same code uploaded the first chunk successfully before you made the change last night. This is the content-range header: bytes 0-4194304/59850810

File size doesn't match headers: file size is 4194304 but 4194305 reported

**Comment by lbross** [comment]
@jkeifer: disregard; Just had a successful upload by updating the end index values. Some clean-up to do but we're on the way!

**Comment by jkeifer** [comment]
@lbross So the problem you noticed was that the end byte in the content-range was the beginning byte of the next chuck. I'm assuming--as I was seeing the same on my side and was doing it this way--that you are making the content-range by setting it to `<beginning_byte>-<chunk_len>/<file_size>`. But the second element of the content range is the ending byte, which is zero-indexed. As such, that second element should be `chunk_len - 1`.

To provide a more concrete example, if you are uploading a 300-byte file using 100-byte chunks, you currently are generating the following content-ranges:

```
0-100/300
100-200/300
200-300/300
```

But those ranges suggest a 101-byte chunk, and that the file is actually 301 bytes (the byte with a zero-indexed index of 300 is actually the 301st byte of the file).

Rather, the content-ranges should be:

```
0-99/300
100-199/300
200-299/300
```

**Comment by jkeifer** [comment]
@lbross I just saw you figured it out once my commented posted. Glad you got it, let me know if you run into anything else.

**Comment by lbross** [comment]
Success! Just able to upload animas_AOI_prms! Woot-woot! Closing!

**Comment by jkeifer** [comment]
Awesome. Glad that worked!
